-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2024.2 (lin64) Build 5239630 Fri Nov 08 22:34:34 MST 2024
-- Date        : Sun Apr 27 06:55:27 2025
-- Host        : pikespeak running 64-bit Ubuntu 22.04.5 LTS
-- Command     : write_vhdl -force -mode synth_stub /home/hkchu/xillybus/vivado-essentials/pcie_ku/pcie_ku_stub.vhdl
-- Design      : pcie_ku
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xcvu095-ffva2104-2-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity pcie_ku is
  Port ( 
    pci_exp_txn : out STD_LOGIC_VECTOR ( 7 downto 0 );
    pci_exp_txp : out STD_LOGIC_VECTOR ( 7 downto 0 );
    pci_exp_rxn : in STD_LOGIC_VECTOR ( 7 downto 0 );
    pci_exp_rxp : in STD_LOGIC_VECTOR ( 7 downto 0 );
    user_clk : out STD_LOGIC;
    user_reset : out STD_LOGIC;
    user_lnk_up : out STD_LOGIC;
    s_axis_rq_tdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s_axis_rq_tkeep : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axis_rq_tlast : in STD_LOGIC;
    s_axis_rq_tready : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axis_rq_tuser : in STD_LOGIC_VECTOR ( 59 downto 0 );
    s_axis_rq_tvalid : in STD_LOGIC;
    m_axis_rc_tdata : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axis_rc_tkeep : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axis_rc_tlast : out STD_LOGIC;
    m_axis_rc_tready : in STD_LOGIC;
    m_axis_rc_tuser : out STD_LOGIC_VECTOR ( 74 downto 0 );
    m_axis_rc_tvalid : out STD_LOGIC;
    m_axis_cq_tdata : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axis_cq_tkeep : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axis_cq_tlast : out STD_LOGIC;
    m_axis_cq_tready : in STD_LOGIC;
    m_axis_cq_tuser : out STD_LOGIC_VECTOR ( 84 downto 0 );
    m_axis_cq_tvalid : out STD_LOGIC;
    s_axis_cc_tdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s_axis_cc_tkeep : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axis_cc_tlast : in STD_LOGIC;
    s_axis_cc_tready : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axis_cc_tuser : in STD_LOGIC_VECTOR ( 32 downto 0 );
    s_axis_cc_tvalid : in STD_LOGIC;
    pcie_rq_seq_num : out STD_LOGIC_VECTOR ( 3 downto 0 );
    pcie_rq_seq_num_vld : out STD_LOGIC;
    pcie_rq_tag : out STD_LOGIC_VECTOR ( 5 downto 0 );
    pcie_rq_tag_av : out STD_LOGIC_VECTOR ( 1 downto 0 );
    pcie_rq_tag_vld : out STD_LOGIC;
    pcie_tfc_nph_av : out STD_LOGIC_VECTOR ( 1 downto 0 );
    pcie_tfc_npd_av : out STD_LOGIC_VECTOR ( 1 downto 0 );
    pcie_cq_np_req : in STD_LOGIC;
    pcie_cq_np_req_count : out STD_LOGIC_VECTOR ( 5 downto 0 );
    cfg_phy_link_down : out STD_LOGIC;
    cfg_phy_link_status : out STD_LOGIC_VECTOR ( 1 downto 0 );
    cfg_negotiated_width : out STD_LOGIC_VECTOR ( 3 downto 0 );
    cfg_current_speed : out STD_LOGIC_VECTOR ( 2 downto 0 );
    cfg_max_payload : out STD_LOGIC_VECTOR ( 2 downto 0 );
    cfg_max_read_req : out STD_LOGIC_VECTOR ( 2 downto 0 );
    cfg_function_status : out STD_LOGIC_VECTOR ( 15 downto 0 );
    cfg_function_power_state : out STD_LOGIC_VECTOR ( 11 downto 0 );
    cfg_vf_status : out STD_LOGIC_VECTOR ( 15 downto 0 );
    cfg_vf_power_state : out STD_LOGIC_VECTOR ( 23 downto 0 );
    cfg_link_power_state : out STD_LOGIC_VECTOR ( 1 downto 0 );
    cfg_err_cor_out : out STD_LOGIC;
    cfg_err_nonfatal_out : out STD_LOGIC;
    cfg_err_fatal_out : out STD_LOGIC;
    cfg_local_error : out STD_LOGIC;
    cfg_ltr_enable : out STD_LOGIC;
    cfg_ltssm_state : out STD_LOGIC_VECTOR ( 5 downto 0 );
    cfg_rcb_status : out STD_LOGIC_VECTOR ( 3 downto 0 );
    cfg_dpa_substate_change : out STD_LOGIC_VECTOR ( 3 downto 0 );
    cfg_obff_enable : out STD_LOGIC_VECTOR ( 1 downto 0 );
    cfg_pl_status_change : out STD_LOGIC;
    cfg_tph_requester_enable : out STD_LOGIC_VECTOR ( 3 downto 0 );
    cfg_tph_st_mode : out STD_LOGIC_VECTOR ( 11 downto 0 );
    cfg_vf_tph_requester_enable : out STD_LOGIC_VECTOR ( 7 downto 0 );
    cfg_vf_tph_st_mode : out STD_LOGIC_VECTOR ( 23 downto 0 );
    cfg_fc_ph : out STD_LOGIC_VECTOR ( 7 downto 0 );
    cfg_fc_pd : out STD_LOGIC_VECTOR ( 11 downto 0 );
    cfg_fc_nph : out STD_LOGIC_VECTOR ( 7 downto 0 );
    cfg_fc_npd : out STD_LOGIC_VECTOR ( 11 downto 0 );
    cfg_fc_cplh : out STD_LOGIC_VECTOR ( 7 downto 0 );
    cfg_fc_cpld : out STD_LOGIC_VECTOR ( 11 downto 0 );
    cfg_fc_sel : in STD_LOGIC_VECTOR ( 2 downto 0 );
    cfg_per_function_number : in STD_LOGIC_VECTOR ( 3 downto 0 );
    cfg_per_function_output_request : in STD_LOGIC;
    cfg_per_function_update_done : out STD_LOGIC;
    cfg_dsn : in STD_LOGIC_VECTOR ( 63 downto 0 );
    cfg_power_state_change_ack : in STD_LOGIC;
    cfg_power_state_change_interrupt : out STD_LOGIC;
    cfg_err_cor_in : in STD_LOGIC;
    cfg_err_uncor_in : in STD_LOGIC;
    cfg_flr_in_process : out STD_LOGIC_VECTOR ( 3 downto 0 );
    cfg_flr_done : in STD_LOGIC_VECTOR ( 3 downto 0 );
    cfg_vf_flr_in_process : out STD_LOGIC_VECTOR ( 7 downto 0 );
    cfg_vf_flr_done : in STD_LOGIC_VECTOR ( 7 downto 0 );
    cfg_link_training_enable : in STD_LOGIC;
    cfg_interrupt_int : in STD_LOGIC_VECTOR ( 3 downto 0 );
    cfg_interrupt_pending : in STD_LOGIC_VECTOR ( 3 downto 0 );
    cfg_interrupt_sent : out STD_LOGIC;
    cfg_interrupt_msi_enable : out STD_LOGIC_VECTOR ( 3 downto 0 );
    cfg_interrupt_msi_vf_enable : out STD_LOGIC_VECTOR ( 7 downto 0 );
    cfg_interrupt_msi_mmenable : out STD_LOGIC_VECTOR ( 11 downto 0 );
    cfg_interrupt_msi_mask_update : out STD_LOGIC;
    cfg_interrupt_msi_data : out STD_LOGIC_VECTOR ( 31 downto 0 );
    cfg_interrupt_msi_select : in STD_LOGIC_VECTOR ( 3 downto 0 );
    cfg_interrupt_msi_int : in STD_LOGIC_VECTOR ( 31 downto 0 );
    cfg_interrupt_msi_pending_status : in STD_LOGIC_VECTOR ( 31 downto 0 );
    cfg_interrupt_msi_pending_status_data_enable : in STD_LOGIC;
    cfg_interrupt_msi_pending_status_function_num : in STD_LOGIC_VECTOR ( 3 downto 0 );
    cfg_interrupt_msi_sent : out STD_LOGIC;
    cfg_interrupt_msi_fail : out STD_LOGIC;
    cfg_interrupt_msi_attr : in STD_LOGIC_VECTOR ( 2 downto 0 );
    cfg_interrupt_msi_tph_present : in STD_LOGIC;
    cfg_interrupt_msi_tph_type : in STD_LOGIC_VECTOR ( 1 downto 0 );
    cfg_interrupt_msi_tph_st_tag : in STD_LOGIC_VECTOR ( 8 downto 0 );
    cfg_interrupt_msi_function_number : in STD_LOGIC_VECTOR ( 3 downto 0 );
    cfg_hot_reset_out : out STD_LOGIC;
    cfg_config_space_enable : in STD_LOGIC;
    cfg_req_pm_transition_l23_ready : in STD_LOGIC;
    cfg_hot_reset_in : in STD_LOGIC;
    cfg_ds_port_number : in STD_LOGIC_VECTOR ( 7 downto 0 );
    cfg_ds_bus_number : in STD_LOGIC_VECTOR ( 7 downto 0 );
    cfg_ds_device_number : in STD_LOGIC_VECTOR ( 4 downto 0 );
    cfg_ds_function_number : in STD_LOGIC_VECTOR ( 2 downto 0 );
    cfg_subsys_vend_id : in STD_LOGIC_VECTOR ( 15 downto 0 );
    sys_clk : in STD_LOGIC;
    sys_clk_gt : in STD_LOGIC;
    sys_reset : in STD_LOGIC;
    pcie_perstn1_in : in STD_LOGIC;
    pcie_perstn0_out : out STD_LOGIC;
    pcie_perstn1_out : out STD_LOGIC;
    phy_rdy_out : out STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of pcie_ku : entity is "pcie_ku,pcie_ku_pcie3_uscale_core_top,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of pcie_ku : entity is "pcie_ku,pcie_ku_pcie3_uscale_core_top,{x_ipProduct=Vivado 2024.2,x_ipVendor=xilinx.com,x_ipLibrary=ip,x_ipName=pcie3_ultrascale,x_ipVersion=4.4,x_ipCoreRevision=21,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,PL_LINK_CAP_MAX_LINK_SPEED=1,PL_LINK_CAP_MAX_LINK_WIDTH=8,USER_CLK_FREQ=3,CORE_CLK_FREQ=1,PLL_TYPE=0,PF0_LINK_CAP_ASPM_SUPPORT=0,C_DATA_WIDTH=64,REF_CLK_FREQ=0,PCIE_LINK_SPEED=2,KEEP_WIDTH=2,ARI_CAP_ENABLE=FALSE,PF0_ARI_CAP_NEXT_FUNC=0x00,AXISTEN_IF_CC_ALIGNMENT_MODE=FALSE,AXISTEN_IF_CQ_ALIGNMENT_MODE=FALSE,AXISTEN_IF_RC_ALIGNMENT_MODE=FALSE,AXISTEN_IF_RC_STRADDLE=FALSE,AXISTEN_IF_RQ_ALIGNMENT_MODE=FALSE,AXISTEN_IF_ENABLE_MSG_ROUTE=0x00000,AXISTEN_IF_ENABLE_RX_MSG_INTFC=FALSE,PF0_AER_CAP_ECRC_CHECK_CAPABLE=FALSE,PF0_AER_CAP_ECRC_GEN_CAPABLE=FALSE,PF0_AER_CAP_NEXTPTR=0x150,PF0_ARI_CAP_NEXTPTR=0x000,VF0_ARI_CAP_NEXTPTR=0x000,VF1_ARI_CAP_NEXTPTR=0x000,VF2_ARI_CAP_NEXTPTR=0x000,VF3_ARI_CAP_NEXTPTR=0x000,VF4_ARI_CAP_NEXTPTR=0x000,VF5_ARI_CAP_NEXTPTR=0x000,PF0_BAR0_APERTURE_SIZE=0x00,PF0_BAR0_CONTROL=0x6,PF0_BAR1_APERTURE_SIZE=0x00,PF0_BAR1_CONTROL=0x0,PF0_BAR2_APERTURE_SIZE=0x00,PF0_BAR2_CONTROL=0x0,PF0_BAR3_APERTURE_SIZE=0x00,PF0_BAR3_CONTROL=0x0,PF0_BAR4_APERTURE_SIZE=0x00,PF0_BAR4_CONTROL=0x0,PF0_BAR5_APERTURE_SIZE=0x00,PF0_BAR5_CONTROL=0x0,PF0_CAPABILITY_POINTER=0x80,PF0_CLASS_CODE=0xFF0000,PF0_VENDOR_ID=0x10EE,PF0_DEVICE_ID=0xEBEB,PF0_DEV_CAP2_128B_CAS_ATOMIC_COMPLETER_SUPPORT=FALSE,PF0_DEV_CAP2_32B_ATOMIC_COMPLETER_SUPPORT=FALSE,PF0_DEV_CAP2_64B_ATOMIC_COMPLETER_SUPPORT=FALSE,PF0_DEV_CAP2_LTR_SUPPORT=FALSE,PF0_DEV_CAP2_OBFF_SUPPORT=0x0,PF0_DEV_CAP2_TPH_COMPLETER_SUPPORT=FALSE,PF0_DEV_CAP_EXT_TAG_SUPPORTED=FALSE,PF0_DEV_CAP_FUNCTION_LEVEL_RESET_CAPABLE=FALSE,PF0_DEV_CAP_MAX_PAYLOAD_SIZE=0x2,PF0_DPA_CAP_NEXTPTR=0x000,PF0_DPA_CAP_SUB_STATE_POWER_ALLOCATION0=0x00,PF0_DPA_CAP_SUB_STATE_POWER_ALLOCATION1=0x00,PF0_DPA_CAP_SUB_STATE_POWER_ALLOCATION2=0x00,PF0_DPA_CAP_SUB_STATE_POWER_ALLOCATION3=0x00,PF0_DPA_CAP_SUB_STATE_POWER_ALLOCATION4=0x00,PF0_DPA_CAP_SUB_STATE_POWER_ALLOCATION5=0x00,PF0_DPA_CAP_SUB_STATE_POWER_ALLOCATION6=0x00,PF0_DPA_CAP_SUB_STATE_POWER_ALLOCATION7=0x00,PF1_DPA_CAP_SUB_STATE_POWER_ALLOCATION0=0x00,PF1_DPA_CAP_SUB_STATE_POWER_ALLOCATION1=0x00,PF1_DPA_CAP_SUB_STATE_POWER_ALLOCATION2=0x00,PF1_DPA_CAP_SUB_STATE_POWER_ALLOCATION3=0x00,PF1_DPA_CAP_SUB_STATE_POWER_ALLOCATION4=0x00,PF1_DPA_CAP_SUB_STATE_POWER_ALLOCATION5=0x00,PF1_DPA_CAP_SUB_STATE_POWER_ALLOCATION6=0x00,PF1_DPA_CAP_SUB_STATE_POWER_ALLOCATION7=0x00,PF0_DSN_CAP_NEXTPTR=0x000,PF0_EXPANSION_ROM_APERTURE_SIZE=0x00,PF0_EXPANSION_ROM_ENABLE=FALSE,PF0_INTERRUPT_PIN=0x0,PF0_LINK_STATUS_SLOT_CLOCK_CONFIG=TRUE,PF0_LTR_CAP_NEXTPTR=0x000,PF0_MSIX_CAP_NEXTPTR=0x00,PF0_MSIX_CAP_PBA_BIR=0,PF0_MSIX_CAP_PBA_OFFSET=0x00000000,PF0_MSIX_CAP_TABLE_BIR=0,PF0_MSIX_CAP_TABLE_OFFSET=0x00000000,PF0_MSIX_CAP_TABLE_SIZE=0x000,PF0_MSI_CAP_MULTIMSGCAP=0,PF0_MSI_CAP_NEXTPTR=0xC0,PF0_PB_CAP_NEXTPTR=0x000,PF0_PM_CAP_NEXTPTR=0x90,PF0_PM_CAP_PMESUPPORT_D0=FALSE,PF0_PM_CAP_PMESUPPORT_D1=FALSE,PF0_PM_CAP_PMESUPPORT_D3HOT=FALSE,PF0_PM_CAP_SUPP_D1_STATE=FALSE,PF0_RBAR_CAP_ENABLE=FALSE,PF0_RBAR_CAP_NEXTPTR=0x000,PF0_RBAR_CAP_SIZE0=0x00000,PF0_RBAR_CAP_SIZE1=0x00000,PF0_RBAR_CAP_SIZE2=0x00000,PF1_RBAR_CAP_SIZE0=0x00000,PF1_RBAR_CAP_SIZE1=0x00000,PF1_RBAR_CAP_SIZE2=0x00000,PF0_REVISION_ID=0x10,PF0_SRIOV_BAR0_APERTURE_SIZE=0x00,PF0_SRIOV_BAR0_CONTROL=0x0,PF0_SRIOV_BAR1_APERTURE_SIZE=0x00,PF0_SRIOV_BAR1_CONTROL=0x0,PF0_SRIOV_BAR2_APERTURE_SIZE=0x00,PF0_SRIOV_BAR2_CONTROL=0x0,PF0_SRIOV_BAR3_APERTURE_SIZE=0x00,PF0_SRIOV_BAR3_CONTROL=0x0,PF0_SRIOV_BAR4_APERTURE_SIZE=0x00,PF0_SRIOV_BAR4_CONTROL=0x0,PF0_SRIOV_BAR5_APERTURE_SIZE=0x00,PF0_SRIOV_BAR5_CONTROL=0x0,PF0_SRIOV_CAP_INITIAL_VF=0x0000,PF0_SRIOV_CAP_NEXTPTR=0x000,PF0_SRIOV_CAP_TOTAL_VF=0x0000,PF0_SRIOV_CAP_VER=0x0,PF0_SRIOV_FIRST_VF_OFFSET=0x0000,PF0_SRIOV_FUNC_DEP_LINK=0x0000,PF0_SRIOV_SUPPORTED_PAGE_SIZE=0x00000553,PF0_SRIOV_VF_DEVICE_ID=0x0000,PF0_SUBSYSTEM_VENDOR_ID=0x10EE,PF0_SUBSYSTEM_ID=0xEBEB,PF0_TPHR_CAP_ENABLE=FALSE,PF0_TPHR_CAP_NEXTPTR=0x000,VF0_TPHR_CAP_NEXTPTR=0x000,VF1_TPHR_CAP_NEXTPTR=0x000,VF2_TPHR_CAP_NEXTPTR=0x000,VF3_TPHR_CAP_NEXTPTR=0x000,VF4_TPHR_CAP_NEXTPTR=0x000,VF5_TPHR_CAP_NEXTPTR=0x000,PF0_TPHR_CAP_ST_MODE_SEL=0x0,PF0_TPHR_CAP_ST_TABLE_LOC=0x0,PF0_TPHR_CAP_ST_TABLE_SIZE=0x000,PF0_TPHR_CAP_VER=0x1,PF1_TPHR_CAP_ST_MODE_SEL=0x0,PF1_TPHR_CAP_ST_TABLE_LOC=0x0,PF1_TPHR_CAP_ST_TABLE_SIZE=0x000,PF1_TPHR_CAP_VER=0x1,VF0_TPHR_CAP_ST_MODE_SEL=0x0,VF0_TPHR_CAP_ST_TABLE_LOC=0x0,VF0_TPHR_CAP_ST_TABLE_SIZE=0x000,VF0_TPHR_CAP_VER=0x1,VF1_TPHR_CAP_ST_MODE_SEL=0x0,VF1_TPHR_CAP_ST_TABLE_LOC=0x0,VF1_TPHR_CAP_ST_TABLE_SIZE=0x000,VF1_TPHR_CAP_VER=0x1,VF2_TPHR_CAP_ST_MODE_SEL=0x0,VF2_TPHR_CAP_ST_TABLE_LOC=0x0,VF2_TPHR_CAP_ST_TABLE_SIZE=0x000,VF2_TPHR_CAP_VER=0x1,VF3_TPHR_CAP_ST_MODE_SEL=0x0,VF3_TPHR_CAP_ST_TABLE_LOC=0x0,VF3_TPHR_CAP_ST_TABLE_SIZE=0x000,VF3_TPHR_CAP_VER=0x1,VF4_TPHR_CAP_ST_MODE_SEL=0x0,VF4_TPHR_CAP_ST_TABLE_LOC=0x0,VF4_TPHR_CAP_ST_TABLE_SIZE=0x000,VF4_TPHR_CAP_VER=0x1,VF5_TPHR_CAP_ST_MODE_SEL=0x0,VF5_TPHR_CAP_ST_TABLE_LOC=0x0,VF5_TPHR_CAP_ST_TABLE_SIZE=0x000,VF5_TPHR_CAP_VER=0x1,PF0_TPHR_CAP_DEV_SPECIFIC_MODE=TRUE,PF0_TPHR_CAP_INT_VEC_MODE=FALSE,PF1_TPHR_CAP_DEV_SPECIFIC_MODE=TRUE,PF1_TPHR_CAP_INT_VEC_MODE=FALSE,VF0_TPHR_CAP_DEV_SPECIFIC_MODE=TRUE,VF0_TPHR_CAP_INT_VEC_MODE=FALSE,VF1_TPHR_CAP_DEV_SPECIFIC_MODE=TRUE,VF1_TPHR_CAP_INT_VEC_MODE=FALSE,VF2_TPHR_CAP_DEV_SPECIFIC_MODE=TRUE,VF2_TPHR_CAP_INT_VEC_MODE=FALSE,VF3_TPHR_CAP_DEV_SPECIFIC_MODE=TRUE,VF3_TPHR_CAP_INT_VEC_MODE=FALSE,VF4_TPHR_CAP_DEV_SPECIFIC_MODE=TRUE,VF4_TPHR_CAP_INT_VEC_MODE=FALSE,VF5_TPHR_CAP_DEV_SPECIFIC_MODE=TRUE,VF5_TPHR_CAP_INT_VEC_MODE=FALSE,PF0_SECONDARY_PCIE_CAP_NEXTPTR=0x000,MCAP_CAP_NEXTPTR=0x000,PF0_VC_CAP_NEXTPTR=0x000,SPARE_WORD1=0x00000000,PF1_AER_CAP_ECRC_CHECK_CAPABLE=FALSE,PF1_AER_CAP_ECRC_GEN_CAPABLE=FALSE,PF1_AER_CAP_NEXTPTR=0x000,PF1_ARI_CAP_NEXTPTR=0x000,PF1_BAR0_APERTURE_SIZE=0x00,PF1_BAR0_CONTROL=0x0,PF1_BAR1_APERTURE_SIZE=0x00,PF1_BAR1_CONTROL=0x0,PF1_BAR2_APERTURE_SIZE=0x00,PF1_BAR2_CONTROL=0x0,PF1_BAR3_APERTURE_SIZE=0x00,PF1_BAR3_CONTROL=0x0,PF1_BAR4_APERTURE_SIZE=0x00,PF1_BAR4_CONTROL=0x0,PF1_BAR5_APERTURE_SIZE=0x00,PF1_BAR5_CONTROL=0x0,PF1_CAPABILITY_POINTER=0x80,PF1_CLASS_CODE=0x070000,PF1_DEVICE_ID=0x8011,PF1_DEV_CAP_MAX_PAYLOAD_SIZE=0x2,PF1_DPA_CAP_NEXTPTR=0x000,PF1_DSN_CAP_NEXTPTR=0x000,PF1_EXPANSION_ROM_APERTURE_SIZE=0x00,PF1_EXPANSION_ROM_ENABLE=FALSE,PF1_INTERRUPT_PIN=0x0,PF1_MSIX_CAP_NEXTPTR=0x00,PF1_MSIX_CAP_PBA_BIR=0,PF1_MSIX_CAP_PBA_OFFSET=0x00000000,PF1_MSIX_CAP_TABLE_BIR=0,PF1_MSIX_CAP_TABLE_OFFSET=0x00000000,PF1_MSIX_CAP_TABLE_SIZE=0x000,PF1_MSI_CAP_MULTIMSGCAP=0,PF1_MSI_CAP_NEXTPTR=0x00,PF1_PB_CAP_NEXTPTR=0x000,PF1_PM_CAP_NEXTPTR=0x00,PF1_RBAR_CAP_ENABLE=FALSE,PF1_RBAR_CAP_NEXTPTR=0x000,PF1_REVISION_ID=0x00,PF1_SRIOV_BAR0_APERTURE_SIZE=0x00,PF1_SRIOV_BAR0_CONTROL=0x0,PF1_SRIOV_BAR1_APERTURE_SIZE=0x00,PF1_SRIOV_BAR1_CONTROL=0x0,PF1_SRIOV_BAR2_APERTURE_SIZE=0x00,PF1_SRIOV_BAR2_CONTROL=0x0,PF1_SRIOV_BAR3_APERTURE_SIZE=0x00,PF1_SRIOV_BAR3_CONTROL=0x0,PF1_SRIOV_BAR4_APERTURE_SIZE=0x00,PF1_SRIOV_BAR4_CONTROL=0x0,PF1_SRIOV_BAR5_APERTURE_SIZE=0x00,PF1_SRIOV_BAR5_CONTROL=0x0,PF1_SRIOV_CAP_INITIAL_VF=0x0000,PF1_SRIOV_CAP_NEXTPTR=0x000,PF1_SRIOV_CAP_TOTAL_VF=0x0000,PF1_SRIOV_CAP_VER=0x0,PF1_SRIOV_FIRST_VF_OFFSET=0x0000,PF1_SRIOV_FUNC_DEP_LINK=0x0001,PF1_SRIOV_SUPPORTED_PAGE_SIZE=0x00000553,PF1_SRIOV_VF_DEVICE_ID=0x0000,PF1_SUBSYSTEM_ID=0x0007,PF1_TPHR_CAP_ENABLE=FALSE,PF1_TPHR_CAP_NEXTPTR=0x000,PL_UPSTREAM_FACING=TRUE,en_msi_per_vec_masking=FALSE,PF0_MSI_CAP_PERVECMASKCAP=FALSE,SRIOV_CAP_ENABLE=FALSE,TL_CREDITS_CD=0x000,TL_CREDITS_CH=0x00,TL_CREDITS_NPD=0x028,TL_CREDITS_NPH=0x20,TL_CREDITS_PD=0x198,TL_CREDITS_PH=0x20,TL_EXTENDED_CFG_EXTEND_INTERFACE_ENABLE=FALSE,ACS_EXT_CAP_ENABLE=FALSE,ACS_CAP_NEXTPTR=0x000,TL_LEGACY_MODE_ENABLE=FALSE,TL_PF_ENABLE_REG=0x0,VF0_CAPABILITY_POINTER=0x80,VF0_MSIX_CAP_PBA_BIR=0,VF0_MSIX_CAP_PBA_OFFSET=0x00000000,VF0_MSIX_CAP_TABLE_BIR=0,VF0_MSIX_CAP_TABLE_OFFSET=0x00000000,VF0_MSIX_CAP_TABLE_SIZE=0x000,VF0_MSI_CAP_MULTIMSGCAP=0,VF0_PM_CAP_NEXTPTR=0x00,VF1_MSIX_CAP_PBA_BIR=0,VF1_MSIX_CAP_PBA_OFFSET=0x00000000,VF1_MSIX_CAP_TABLE_BIR=0,VF1_MSIX_CAP_TABLE_OFFSET=0x00000000,VF1_MSIX_CAP_TABLE_SIZE=0x000,VF1_MSI_CAP_MULTIMSGCAP=0,VF1_PM_CAP_NEXTPTR=0x00,VF2_MSIX_CAP_PBA_BIR=0,VF2_MSIX_CAP_PBA_OFFSET=0x00000000,VF2_MSIX_CAP_TABLE_BIR=0,VF2_MSIX_CAP_TABLE_OFFSET=0x00000000,VF2_MSIX_CAP_TABLE_SIZE=0x000,VF2_MSI_CAP_MULTIMSGCAP=0,VF2_PM_CAP_NEXTPTR=0x00,VF3_MSIX_CAP_PBA_BIR=0,VF3_MSIX_CAP_PBA_OFFSET=0x00000000,VF3_MSIX_CAP_TABLE_BIR=0,VF3_MSIX_CAP_TABLE_OFFSET=0x00000000,VF3_MSIX_CAP_TABLE_SIZE=0x000,VF3_MSI_CAP_MULTIMSGCAP=0,VF3_PM_CAP_NEXTPTR=0x00,VF4_MSIX_CAP_PBA_BIR=0,VF4_MSIX_CAP_PBA_OFFSET=0x00000000,VF4_MSIX_CAP_TABLE_BIR=0,VF4_MSIX_CAP_TABLE_OFFSET=0x00000000,VF4_MSIX_CAP_TABLE_SIZE=0x000,VF4_MSI_CAP_MULTIMSGCAP=0,VF4_PM_CAP_NEXTPTR=0x00,VF5_MSIX_CAP_PBA_BIR=0,VF5_MSIX_CAP_PBA_OFFSET=0x00000000,VF5_MSIX_CAP_TABLE_BIR=0,VF5_MSIX_CAP_TABLE_OFFSET=0x00000000,VF5_MSIX_CAP_TABLE_SIZE=0x000,VF5_MSI_CAP_MULTIMSGCAP=0,VF5_PM_CAP_NEXTPTR=0x00,COMPLETION_SPACE=16KB,gen_x0y0_xdc=1,gen_x0y1_xdc=0,gen_x0y2_xdc=0,gen_x0y3_xdc=0,gen_x0y4_xdc=0,gen_x0y5_xdc=0,xlnx_ref_board=0,pcie_blk_locn=0,PIPE_SIM=FALSE,AXISTEN_IF_ENABLE_CLIENT_TAG=TRUE,PCIE_USE_MODE=2.0,PCIE_FAST_CONFIG=NONE,EXT_STARTUP_PRIMITIVE=FALSE,PL_INTERFACE=FALSE,PCIE_CONFIGURATION=FALSE,CFG_STATUS_IF=TRUE,GT_TX_PD=FALSE,TX_FC_IF=TRUE,CFG_EXT_IF=FALSE,CFG_FC_IF=TRUE,PER_FUNC_STATUS_IF=FALSE,CFG_MGMT_IF=FALSE,RCV_MSG_IF=FALSE,CFG_TX_MSG_IF=FALSE,CFG_CTL_IF=TRUE,MSI_EN=TRUE,MSIX_EN=FALSE,PCIE3_DRP=FALSE,DIS_GT_WIZARD=FALSE,TRANSCEIVER_CTRL_STATUS_PORTS=FALSE,SHARED_LOGIC=1,DEDICATE_PERST=TRUE,SYS_RESET_POLARITY=0,MCAP_ENABLEMENT=NONE,MCAP_FPGA_BITSTREAM_VERSION=0x00000000,PHY_LP_TXPRESET=4,EXT_CH_GT_DRP=FALSE,EN_GT_SELECTION=FALSE,SELECT_QUAD=GTH_Quad_225,silicon_revision=Production,DEV_PORT_TYPE=0,RX_DETECT=0,ENABLE_IBERT=FALSE,ENABLE_DRP_EYESCANRST_WOIBERT=FALSE,DBG_DESCRAMBLE_EN=FALSE,ENABLE_JTAG_DBG=FALSE,ENABLE_LTSSM_DBG=FALSE,AXISTEN_IF_CC_PARITY_CHK=FALSE,AXISTEN_IF_RQ_PARITY_CHK=FALSE,ENABLE_AUTO_RXEQ=FALSE,GTWIZ_IN_CORE=1,INS_LOSS_PROFILE=Backplane,PM_ENABLE_L23_ENTRY=FALSE,BMD_PIO_MODE=FALSE,MULT_PF_DES=TRUE,ENABLE_GT_V1_5=FALSE,EXT_XVC_VSEC_ENABLE=FALSE,GT_DRP_CLK_SRC=0,FREE_RUN_FREQ=0}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of pcie_ku : entity is "yes";
end pcie_ku;

architecture stub of pcie_ku is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "pci_exp_txn[7:0],pci_exp_txp[7:0],pci_exp_rxn[7:0],pci_exp_rxp[7:0],user_clk,user_reset,user_lnk_up,s_axis_rq_tdata[63:0],s_axis_rq_tkeep[1:0],s_axis_rq_tlast,s_axis_rq_tready[3:0],s_axis_rq_tuser[59:0],s_axis_rq_tvalid,m_axis_rc_tdata[63:0],m_axis_rc_tkeep[1:0],m_axis_rc_tlast,m_axis_rc_tready,m_axis_rc_tuser[74:0],m_axis_rc_tvalid,m_axis_cq_tdata[63:0],m_axis_cq_tkeep[1:0],m_axis_cq_tlast,m_axis_cq_tready,m_axis_cq_tuser[84:0],m_axis_cq_tvalid,s_axis_cc_tdata[63:0],s_axis_cc_tkeep[1:0],s_axis_cc_tlast,s_axis_cc_tready[3:0],s_axis_cc_tuser[32:0],s_axis_cc_tvalid,pcie_rq_seq_num[3:0],pcie_rq_seq_num_vld,pcie_rq_tag[5:0],pcie_rq_tag_av[1:0],pcie_rq_tag_vld,pcie_tfc_nph_av[1:0],pcie_tfc_npd_av[1:0],pcie_cq_np_req,pcie_cq_np_req_count[5:0],cfg_phy_link_down,cfg_phy_link_status[1:0],cfg_negotiated_width[3:0],cfg_current_speed[2:0],cfg_max_payload[2:0],cfg_max_read_req[2:0],cfg_function_status[15:0],cfg_function_power_state[11:0],cfg_vf_status[15:0],cfg_vf_power_state[23:0],cfg_link_power_state[1:0],cfg_err_cor_out,cfg_err_nonfatal_out,cfg_err_fatal_out,cfg_local_error,cfg_ltr_enable,cfg_ltssm_state[5:0],cfg_rcb_status[3:0],cfg_dpa_substate_change[3:0],cfg_obff_enable[1:0],cfg_pl_status_change,cfg_tph_requester_enable[3:0],cfg_tph_st_mode[11:0],cfg_vf_tph_requester_enable[7:0],cfg_vf_tph_st_mode[23:0],cfg_fc_ph[7:0],cfg_fc_pd[11:0],cfg_fc_nph[7:0],cfg_fc_npd[11:0],cfg_fc_cplh[7:0],cfg_fc_cpld[11:0],cfg_fc_sel[2:0],cfg_per_function_number[3:0],cfg_per_function_output_request,cfg_per_function_update_done,cfg_dsn[63:0],cfg_power_state_change_ack,cfg_power_state_change_interrupt,cfg_err_cor_in,cfg_err_uncor_in,cfg_flr_in_process[3:0],cfg_flr_done[3:0],cfg_vf_flr_in_process[7:0],cfg_vf_flr_done[7:0],cfg_link_training_enable,cfg_interrupt_int[3:0],cfg_interrupt_pending[3:0],cfg_interrupt_sent,cfg_interrupt_msi_enable[3:0],cfg_interrupt_msi_vf_enable[7:0],cfg_interrupt_msi_mmenable[11:0],cfg_interrupt_msi_mask_update,cfg_interrupt_msi_data[31:0],cfg_interrupt_msi_select[3:0],cfg_interrupt_msi_int[31:0],cfg_interrupt_msi_pending_status[31:0],cfg_interrupt_msi_pending_status_data_enable,cfg_interrupt_msi_pending_status_function_num[3:0],cfg_interrupt_msi_sent,cfg_interrupt_msi_fail,cfg_interrupt_msi_attr[2:0],cfg_interrupt_msi_tph_present,cfg_interrupt_msi_tph_type[1:0],cfg_interrupt_msi_tph_st_tag[8:0],cfg_interrupt_msi_function_number[3:0],cfg_hot_reset_out,cfg_config_space_enable,cfg_req_pm_transition_l23_ready,cfg_hot_reset_in,cfg_ds_port_number[7:0],cfg_ds_bus_number[7:0],cfg_ds_device_number[4:0],cfg_ds_function_number[2:0],cfg_subsys_vend_id[15:0],sys_clk,sys_clk_gt,sys_reset,pcie_perstn1_in,pcie_perstn0_out,pcie_perstn1_out,phy_rdy_out";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of pci_exp_txn : signal is "xilinx.com:interface:pcie_7x_mgt:1.0 pcie_7x_mgt txn";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of pci_exp_txn : signal is "master";
  attribute X_INTERFACE_INFO of pci_exp_txp : signal is "xilinx.com:interface:pcie_7x_mgt:1.0 pcie_7x_mgt txp";
  attribute X_INTERFACE_INFO of pci_exp_rxn : signal is "xilinx.com:interface:pcie_7x_mgt:1.0 pcie_7x_mgt rxn";
  attribute X_INTERFACE_INFO of pci_exp_rxp : signal is "xilinx.com:interface:pcie_7x_mgt:1.0 pcie_7x_mgt rxp";
  attribute X_INTERFACE_INFO of user_clk : signal is "xilinx.com:signal:clock:1.0 CLK.user_clk CLK";
  attribute X_INTERFACE_MODE of user_clk : signal is "master";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of user_clk : signal is "XIL_INTERFACENAME CLK.user_clk, ASSOCIATED_BUSIF m_axis_cq:s_axis_cc:s_axis_rq:m_axis_rc, FREQ_HZ 125000000, ASSOCIATED_RESET user_reset, FREQ_TOLERANCE_HZ 0, PHASE 0.0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of user_reset : signal is "xilinx.com:signal:reset:1.0 RST.user_reset RST";
  attribute X_INTERFACE_MODE of user_reset : signal is "master";
  attribute X_INTERFACE_PARAMETER of user_reset : signal is "XIL_INTERFACENAME RST.user_reset, POLARITY ACTIVE_HIGH, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axis_rq_tdata : signal is "xilinx.com:interface:axis:1.0 s_axis_rq TDATA";
  attribute X_INTERFACE_MODE of s_axis_rq_tdata : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axis_rq_tdata : signal is "XIL_INTERFACENAME s_axis_rq, TDATA_NUM_BYTES 8, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 60, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 1, HAS_TLAST 1, FREQ_HZ 100000000, PHASE 0.0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axis_rq_tkeep : signal is "xilinx.com:interface:axis:1.0 s_axis_rq TKEEP";
  attribute X_INTERFACE_INFO of s_axis_rq_tlast : signal is "xilinx.com:interface:axis:1.0 s_axis_rq TLAST";
  attribute X_INTERFACE_INFO of s_axis_rq_tready : signal is "xilinx.com:interface:axis:1.0 s_axis_rq TREADY";
  attribute X_INTERFACE_INFO of s_axis_rq_tuser : signal is "xilinx.com:interface:axis:1.0 s_axis_rq TUSER";
  attribute X_INTERFACE_INFO of s_axis_rq_tvalid : signal is "xilinx.com:interface:axis:1.0 s_axis_rq TVALID";
  attribute X_INTERFACE_INFO of m_axis_rc_tdata : signal is "xilinx.com:interface:axis:1.0 m_axis_rc TDATA";
  attribute X_INTERFACE_MODE of m_axis_rc_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axis_rc_tdata : signal is "XIL_INTERFACENAME m_axis_rc, TDATA_NUM_BYTES 8, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 75, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 1, HAS_TLAST 1, FREQ_HZ 100000000, PHASE 0.0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axis_rc_tkeep : signal is "xilinx.com:interface:axis:1.0 m_axis_rc TKEEP";
  attribute X_INTERFACE_INFO of m_axis_rc_tlast : signal is "xilinx.com:interface:axis:1.0 m_axis_rc TLAST";
  attribute X_INTERFACE_INFO of m_axis_rc_tready : signal is "xilinx.com:interface:axis:1.0 m_axis_rc TREADY";
  attribute X_INTERFACE_INFO of m_axis_rc_tuser : signal is "xilinx.com:interface:axis:1.0 m_axis_rc TUSER";
  attribute X_INTERFACE_INFO of m_axis_rc_tvalid : signal is "xilinx.com:interface:axis:1.0 m_axis_rc TVALID";
  attribute X_INTERFACE_INFO of m_axis_cq_tdata : signal is "xilinx.com:interface:axis:1.0 m_axis_cq TDATA";
  attribute X_INTERFACE_MODE of m_axis_cq_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axis_cq_tdata : signal is "XIL_INTERFACENAME m_axis_cq, TDATA_NUM_BYTES 8, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 85, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 1, HAS_TLAST 1, FREQ_HZ 100000000, PHASE 0.0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axis_cq_tkeep : signal is "xilinx.com:interface:axis:1.0 m_axis_cq TKEEP";
  attribute X_INTERFACE_INFO of m_axis_cq_tlast : signal is "xilinx.com:interface:axis:1.0 m_axis_cq TLAST";
  attribute X_INTERFACE_INFO of m_axis_cq_tready : signal is "xilinx.com:interface:axis:1.0 m_axis_cq TREADY";
  attribute X_INTERFACE_INFO of m_axis_cq_tuser : signal is "xilinx.com:interface:axis:1.0 m_axis_cq TUSER";
  attribute X_INTERFACE_INFO of m_axis_cq_tvalid : signal is "xilinx.com:interface:axis:1.0 m_axis_cq TVALID";
  attribute X_INTERFACE_INFO of s_axis_cc_tdata : signal is "xilinx.com:interface:axis:1.0 s_axis_cc TDATA";
  attribute X_INTERFACE_MODE of s_axis_cc_tdata : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axis_cc_tdata : signal is "XIL_INTERFACENAME s_axis_cc, TDATA_NUM_BYTES 8, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 33, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 1, HAS_TLAST 1, FREQ_HZ 100000000, PHASE 0.0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axis_cc_tkeep : signal is "xilinx.com:interface:axis:1.0 s_axis_cc TKEEP";
  attribute X_INTERFACE_INFO of s_axis_cc_tlast : signal is "xilinx.com:interface:axis:1.0 s_axis_cc TLAST";
  attribute X_INTERFACE_INFO of s_axis_cc_tready : signal is "xilinx.com:interface:axis:1.0 s_axis_cc TREADY";
  attribute X_INTERFACE_INFO of s_axis_cc_tuser : signal is "xilinx.com:interface:axis:1.0 s_axis_cc TUSER";
  attribute X_INTERFACE_INFO of s_axis_cc_tvalid : signal is "xilinx.com:interface:axis:1.0 s_axis_cc TVALID";
  attribute X_INTERFACE_INFO of pcie_rq_seq_num : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status rq_seq_num";
  attribute X_INTERFACE_MODE of pcie_rq_seq_num : signal is "master";
  attribute X_INTERFACE_INFO of pcie_rq_seq_num_vld : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status rq_seq_num_vld";
  attribute X_INTERFACE_INFO of pcie_rq_tag : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status rq_tag";
  attribute X_INTERFACE_INFO of pcie_rq_tag_av : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status rq_tag_av";
  attribute X_INTERFACE_INFO of pcie_rq_tag_vld : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status rq_tag_vld";
  attribute X_INTERFACE_INFO of pcie_tfc_nph_av : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status tfc_nph_av, xilinx.com:interface:pcie3_transmit_fc:1.0 pcie3_transmit_fc nph_av";
  attribute X_INTERFACE_MODE of pcie_tfc_nph_av : signal is "master pcie3_transmit_fc";
  attribute X_INTERFACE_INFO of pcie_tfc_npd_av : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status tfc_npd_av, xilinx.com:interface:pcie3_transmit_fc:1.0 pcie3_transmit_fc npd_av";
  attribute X_INTERFACE_INFO of pcie_cq_np_req : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status cq_np_req";
  attribute X_INTERFACE_INFO of pcie_cq_np_req_count : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status cq_np_req_count";
  attribute X_INTERFACE_INFO of cfg_phy_link_down : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status phy_link_down";
  attribute X_INTERFACE_INFO of cfg_phy_link_status : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status phy_link_status";
  attribute X_INTERFACE_INFO of cfg_negotiated_width : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status negotiated_width";
  attribute X_INTERFACE_INFO of cfg_current_speed : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status current_speed";
  attribute X_INTERFACE_INFO of cfg_max_payload : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status max_payload";
  attribute X_INTERFACE_INFO of cfg_max_read_req : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status max_read_req";
  attribute X_INTERFACE_INFO of cfg_function_status : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status function_status";
  attribute X_INTERFACE_INFO of cfg_function_power_state : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status function_power_state";
  attribute X_INTERFACE_INFO of cfg_vf_status : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status vf_status";
  attribute X_INTERFACE_INFO of cfg_vf_power_state : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status vf_power_state";
  attribute X_INTERFACE_INFO of cfg_link_power_state : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status link_power_state";
  attribute X_INTERFACE_INFO of cfg_err_cor_out : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status err_cor_out";
  attribute X_INTERFACE_INFO of cfg_err_nonfatal_out : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status err_nonfatal_out";
  attribute X_INTERFACE_INFO of cfg_err_fatal_out : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status err_fatal_out";
  attribute X_INTERFACE_INFO of cfg_local_error : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control local_error";
  attribute X_INTERFACE_MODE of cfg_local_error : signal is "slave";
  attribute X_INTERFACE_INFO of cfg_ltr_enable : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status ltr_enable";
  attribute X_INTERFACE_INFO of cfg_ltssm_state : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status ltssm_state";
  attribute X_INTERFACE_INFO of cfg_rcb_status : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status rcb_status";
  attribute X_INTERFACE_INFO of cfg_dpa_substate_change : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status dpa_substate_change";
  attribute X_INTERFACE_INFO of cfg_obff_enable : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status obff_enable";
  attribute X_INTERFACE_INFO of cfg_pl_status_change : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status pl_status_change";
  attribute X_INTERFACE_INFO of cfg_tph_requester_enable : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status tph_requester_enable";
  attribute X_INTERFACE_INFO of cfg_tph_st_mode : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status tph_st_mode";
  attribute X_INTERFACE_INFO of cfg_vf_tph_requester_enable : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status vf_tph_requester_enable";
  attribute X_INTERFACE_INFO of cfg_vf_tph_st_mode : signal is "xilinx.com:interface:pcie3_cfg_status:1.0 pcie3_cfg_status vf_tph_st_mode";
  attribute X_INTERFACE_INFO of cfg_fc_ph : signal is "xilinx.com:interface:pcie_cfg_fc:1.0 pcie_cfg_fc PH";
  attribute X_INTERFACE_MODE of cfg_fc_ph : signal is "master";
  attribute X_INTERFACE_INFO of cfg_fc_pd : signal is "xilinx.com:interface:pcie_cfg_fc:1.0 pcie_cfg_fc PD";
  attribute X_INTERFACE_INFO of cfg_fc_nph : signal is "xilinx.com:interface:pcie_cfg_fc:1.0 pcie_cfg_fc NPH";
  attribute X_INTERFACE_INFO of cfg_fc_npd : signal is "xilinx.com:interface:pcie_cfg_fc:1.0 pcie_cfg_fc NPD";
  attribute X_INTERFACE_INFO of cfg_fc_cplh : signal is "xilinx.com:interface:pcie_cfg_fc:1.0 pcie_cfg_fc CPLH";
  attribute X_INTERFACE_INFO of cfg_fc_cpld : signal is "xilinx.com:interface:pcie_cfg_fc:1.0 pcie_cfg_fc CPLD";
  attribute X_INTERFACE_INFO of cfg_fc_sel : signal is "xilinx.com:interface:pcie_cfg_fc:1.0 pcie_cfg_fc SEL";
  attribute X_INTERFACE_INFO of cfg_per_function_number : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control per_function_number";
  attribute X_INTERFACE_INFO of cfg_per_function_output_request : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control per_function_output_request";
  attribute X_INTERFACE_INFO of cfg_per_function_update_done : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control per_function_update_done";
  attribute X_INTERFACE_INFO of cfg_dsn : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control dsn";
  attribute X_INTERFACE_INFO of cfg_power_state_change_ack : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control power_state_change_ack";
  attribute X_INTERFACE_INFO of cfg_power_state_change_interrupt : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control power_state_change_interrupt";
  attribute X_INTERFACE_INFO of cfg_err_cor_in : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control err_cor_in";
  attribute X_INTERFACE_INFO of cfg_err_uncor_in : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control err_uncor_in";
  attribute X_INTERFACE_INFO of cfg_flr_in_process : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control flr_in_process";
  attribute X_INTERFACE_INFO of cfg_flr_done : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control flr_done";
  attribute X_INTERFACE_INFO of cfg_vf_flr_in_process : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control vf_flr_in_process";
  attribute X_INTERFACE_INFO of cfg_vf_flr_done : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control vf_flr_done";
  attribute X_INTERFACE_INFO of cfg_link_training_enable : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control link_training_enable";
  attribute X_INTERFACE_INFO of cfg_interrupt_int : signal is "xilinx.com:interface:pcie3_cfg_interrupt:1.0 pcie3_cfg_interrupt INTx_VECTOR";
  attribute X_INTERFACE_MODE of cfg_interrupt_int : signal is "slave";
  attribute X_INTERFACE_INFO of cfg_interrupt_pending : signal is "xilinx.com:interface:pcie3_cfg_interrupt:1.0 pcie3_cfg_interrupt PENDING";
  attribute X_INTERFACE_INFO of cfg_interrupt_sent : signal is "xilinx.com:interface:pcie3_cfg_interrupt:1.0 pcie3_cfg_interrupt SENT";
  attribute X_INTERFACE_INFO of cfg_interrupt_msi_enable : signal is "xilinx.com:interface:pcie3_cfg_msi:1.0 pcie3_cfg_msi enable";
  attribute X_INTERFACE_MODE of cfg_interrupt_msi_enable : signal is "slave";
  attribute X_INTERFACE_INFO of cfg_interrupt_msi_vf_enable : signal is "xilinx.com:interface:pcie3_cfg_msi:1.0 pcie3_cfg_msi vf_enable";
  attribute X_INTERFACE_INFO of cfg_interrupt_msi_mmenable : signal is "xilinx.com:interface:pcie3_cfg_msi:1.0 pcie3_cfg_msi mmenable";
  attribute X_INTERFACE_INFO of cfg_interrupt_msi_mask_update : signal is "xilinx.com:interface:pcie3_cfg_msi:1.0 pcie3_cfg_msi mask_update";
  attribute X_INTERFACE_INFO of cfg_interrupt_msi_data : signal is "xilinx.com:interface:pcie3_cfg_msi:1.0 pcie3_cfg_msi data";
  attribute X_INTERFACE_INFO of cfg_interrupt_msi_select : signal is "xilinx.com:interface:pcie3_cfg_msi:1.0 pcie3_cfg_msi select";
  attribute X_INTERFACE_INFO of cfg_interrupt_msi_int : signal is "xilinx.com:interface:pcie3_cfg_msi:1.0 pcie3_cfg_msi int_vector";
  attribute X_INTERFACE_INFO of cfg_interrupt_msi_pending_status : signal is "xilinx.com:interface:pcie3_cfg_msi:1.0 pcie3_cfg_msi pending_status";
  attribute X_INTERFACE_INFO of cfg_interrupt_msi_pending_status_data_enable : signal is "xilinx.com:interface:pcie3_cfg_msi:1.0 pcie3_cfg_msi pending_status_data_enable";
  attribute X_INTERFACE_INFO of cfg_interrupt_msi_pending_status_function_num : signal is "xilinx.com:interface:pcie3_cfg_msi:1.0 pcie3_cfg_msi pending_status_function_num";
  attribute X_INTERFACE_INFO of cfg_interrupt_msi_sent : signal is "xilinx.com:interface:pcie3_cfg_msi:1.0 pcie3_cfg_msi sent";
  attribute X_INTERFACE_INFO of cfg_interrupt_msi_fail : signal is "xilinx.com:interface:pcie3_cfg_msi:1.0 pcie3_cfg_msi fail";
  attribute X_INTERFACE_INFO of cfg_interrupt_msi_attr : signal is "xilinx.com:interface:pcie3_cfg_msi:1.0 pcie3_cfg_msi attr";
  attribute X_INTERFACE_INFO of cfg_interrupt_msi_tph_present : signal is "xilinx.com:interface:pcie3_cfg_msi:1.0 pcie3_cfg_msi tph_present";
  attribute X_INTERFACE_INFO of cfg_interrupt_msi_tph_type : signal is "xilinx.com:interface:pcie3_cfg_msi:1.0 pcie3_cfg_msi tph_type";
  attribute X_INTERFACE_INFO of cfg_interrupt_msi_tph_st_tag : signal is "xilinx.com:interface:pcie3_cfg_msi:1.0 pcie3_cfg_msi tph_st_tag";
  attribute X_INTERFACE_INFO of cfg_interrupt_msi_function_number : signal is "xilinx.com:interface:pcie3_cfg_msi:1.0 pcie3_cfg_msi function_number";
  attribute X_INTERFACE_INFO of cfg_hot_reset_out : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control hot_reset_out";
  attribute X_INTERFACE_INFO of cfg_config_space_enable : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control config_space_enable";
  attribute X_INTERFACE_INFO of cfg_req_pm_transition_l23_ready : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control req_pm_transition_l23_ready";
  attribute X_INTERFACE_INFO of cfg_hot_reset_in : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control hot_reset_in";
  attribute X_INTERFACE_INFO of cfg_ds_port_number : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control ds_port_number";
  attribute X_INTERFACE_INFO of cfg_ds_bus_number : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control ds_bus_number";
  attribute X_INTERFACE_INFO of cfg_ds_device_number : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control ds_device_number";
  attribute X_INTERFACE_INFO of cfg_ds_function_number : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control ds_function_number";
  attribute X_INTERFACE_INFO of cfg_subsys_vend_id : signal is "xilinx.com:interface:pcie3_cfg_control:1.0 pcie3_cfg_control subsys_vend_id";
  attribute X_INTERFACE_INFO of sys_clk : signal is "xilinx.com:signal:clock:1.0 CLK.sys_clk CLK";
  attribute X_INTERFACE_MODE of sys_clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of sys_clk : signal is "XIL_INTERFACENAME CLK.sys_clk, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of sys_clk_gt : signal is "xilinx.com:signal:clock:1.0 CLK.sys_clk_gt CLK";
  attribute X_INTERFACE_MODE of sys_clk_gt : signal is "slave";
  attribute X_INTERFACE_PARAMETER of sys_clk_gt : signal is "XIL_INTERFACENAME CLK.sys_clk_gt, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of sys_reset : signal is "xilinx.com:signal:reset:1.0 RST.sys_rst RST";
  attribute X_INTERFACE_MODE of sys_reset : signal is "slave";
  attribute X_INTERFACE_PARAMETER of sys_reset : signal is "XIL_INTERFACENAME RST.sys_rst, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "pcie_ku_pcie3_uscale_core_top,Vivado 2024.2";
begin
end;
