# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hkchu/xillybus/vivado-essentials/fifo_8x2048/fifo_8x2048.xci
# IP: The module: 'fifo_8x2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hkchu/xillybus/vivado-essentials/fifo_8x2048/fifo_8x2048.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8x2048'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/hkchu/xillybus/vivado-essentials/fifo_8x2048/fifo_8x2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/hkchu/xillybus/vivado-essentials/fifo_8x2048/fifo_8x2048.xci
# IP: The module: 'fifo_8x2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hkchu/xillybus/vivado-essentials/fifo_8x2048/fifo_8x2048.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/hkchu/xillybus/vivado-essentials/fifo_8x2048/fifo_8x2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
