# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hkchu/xillybus/verilog/fifo_32x512/fifo_32x512.xci
# IP: The module: 'fifo_32x512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hkchu/xillybus/verilog/fifo_32x512/fifo_32x512.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_32x512'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/hkchu/xillybus/verilog/fifo_32x512/fifo_32x512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_32x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/hkchu/xillybus/verilog/fifo_32x512/fifo_32x512.xci
# IP: The module: 'fifo_32x512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hkchu/xillybus/verilog/fifo_32x512/fifo_32x512.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_32x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/hkchu/xillybus/verilog/fifo_32x512/fifo_32x512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_32x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
